"""add optional assigned_to

Revision ID: 44b28ab8f121
Revises: df740c1b7552
Create Date: 2026-06-13 20:07:59.336407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44b28ab8f121'
down_revision: Union[str, Sequence[str], None] = 'df740c1b7552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    op.add_column('task', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('parent_task_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'task', 'task', ['parent_task_id'], ['uid'])
    op.drop_column('task', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'parent_task_id')
    op.drop_column('task', 'assigned_to')
    op.create_table('project',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('project_pkey'))
    )
    # ### end Alembic commands ###
