"""add roles to users

Revision ID: 485acb82a708
Revises: 44b28ab8f121
Create Date: 2026-06-27 16:53:18.177153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '485acb82a708'
down_revision: Union[str, Sequence[str], None] = '44b28ab8f121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    op.add_column('users', sa.Column('role', sa.VARCHAR(), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.create_table('project',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('project_pkey'))
    )
    # ### end Alembic commands ###
