"""rlate user to task

Revision ID: 774b093be030
Revises: 51b6acf8e6e8
Create Date: 2026-06-27 18:23:10.506825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '774b093be030'
down_revision: Union[str, Sequence[str], None] = '51b6acf8e6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user_uid', sa.UUID(), nullable=True))
    op.alter_column('task', 'assigned_to',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.create_foreign_key(None, 'task', 'users', ['assigned_to'], ['uid'])
    op.create_foreign_key(None, 'task', 'users', ['user_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.alter_column('task', 'assigned_to',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('task', 'user_uid')
    # ### end Alembic commands ###
