"""rlate user to task

Revision ID: c6510602a202
Revises: 6460d717f50f
Create Date: 2026-06-27 18:28:44.424043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'c6510602a202'
down_revision: Union[str, Sequence[str], None] = '6460d717f50f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Drop the old integer column entirely
    op.drop_column('task', 'assigned_to')
    
    # 2. Add the brand new clean UUID columns
    op.add_column('task', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.add_column('task', sa.Column('assigned_to', sa.Uuid(), nullable=True))
    
    # 3. Create the foreign key links to your users table
    op.create_foreign_key(None, 'task', 'users', ['user_uid'], ['uid'])
    op.create_foreign_key(None, 'task', 'users', ['assigned_to'], ['uid'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.alter_column('task', 'assigned_to',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('task', 'user_uid')
    # ### end Alembic commands ###
